baseurl = "https://phosphofructo.github.io/"
languageCode = "en-us"
title = "Personal Website"
theme = "blackburn"
author = "Darya Akimova"
copyright = "&copy; 2018. All rights reserved."
canonifyurls = true
paginate = 10
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "A Data Science Portfolio"
  brand = "Darya Akimova"
  #googleAnalytics = "Your Google Analytics tracking ID"
  #disqus = "Your Disqus shortname"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
  dateFormat = "02 Jan 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-code fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 3
    identifier = "about"
    url = "/about/"


[social]
  # Link your social networking accouns to the side menu
  # by entering your username or ID.
  twitter = "*"
  github = "phosphofructo"
  linkedin = "darya-akimova-b45066a2"
